### ISSUE TITLE
Mozilla Festival Social - Meta Ticket

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#54]
We chatted with Audrey today about plans for MozFest social. 

### Request for template background graphics:
- [ ] for Instagram Stories
- [ ] for wrap up posts
- [ ] with editable text placeholder

### Request for specific graphics:

**Sponsorship**
- [ ]  something to share with sponsors

**Tickets**
- [ ] various of ticket graphics for sales

**MozFest House**
- [ ] countdown

**Live Speakers (Dialogues & Debates)**
- [ ] for Twitter/Instagram Stories

**Wranglers**
- [ ] mini interview clips for Twitter/Instagram Stories

________________________

### Calendar
TBD Audrey to send schedule screenshot

**Comment by sabrinang** [comment]
Note: To prioritize sponsorship graphics. Sponsorship graphics to be sent out early next week as we’re announcing sponsors daily next week then they’ll post as they see fit (example: "Proud to be a sponsor of #MozFest").

**Comment by AwesomeAudrey** [comment]
Hi All,

Thanks for this! Let me know if I'm not using github correctly! Below is the gist of what's being shared about sponsors from us and them.. For the most part, I don't need images for our posts about sponsors as we can use the link previews on Twitter generated by their sites, however sponsors may need an image to talk about it on their channels (see Tweet 3)

- Tweet 1 (between October 3-21): Mozilla announcement tweet of Sponsor’s MozFest sponsorship, something similar to: “We're pleased to announce @internetsociety as a Champion level sponsor of #MozFest this year! Check out their blog post as to why they are excited to support MozFest [link to Sponsor blog post (subject to Mozilla approval)”.
- Tweet 2 (between October 3-23): Mozilla tweet linking to MozFest website sponsorship page, something similar to: “We can’t wait to see everyone at MozFest in three weeks. Thanks to our amazing group of 2019 #MozFest sponsors [@Each Sponsor)”
**- Tweet 3 (between October 4-24): Mozilla retweets a tweet from Sponsor announcing their involvement in MozFest, something similar to: “We’re thrilled to be sponsoring the 10th Anniversary of #MozFest year. We can’t wait to see you there!”**
- Tweet 4 (October 24): Mozilla tweets a kickoff to MozFest with a thank you to sponsors, something similar to: “Excited to see everyone tomorrow. Thanks to our sponsors for supporting our event! [@ Each Sponsor] [Include photo of the sponsorship banner]”
- Tweet 5 (October 26-27): Mozilla retweets a tweet from Sponsor about MozFest, something similar to: “Welcome to MozFest! Come visit us in the Privacy and Security space and visit our encrypted wall! [include a photo of the Event]”

This is what I'm planning to share during MozFest, there will be more but these are some of the content hooks I wanted to prepare for in advance:
<img width="1179" alt="Screenshot 2019-10-11 at 07 53 58" src="https://user-images.githubusercontent.com/7354847/66749123-e5321500-ee80-11e9-8d00-84761638a4d2.png">
<img width="1175" alt="Screenshot 2019-10-11 at 07 54 16" src="https://user-images.githubusercontent.com/7354847/66749124-e5321500-ee80-11e9-9acc-f9af8958f3b8.png">
<img width="1178" alt="Screenshot 2019-10-11 at 07 54 36" src="https://user-images.githubusercontent.com/7354847/66749125-e5321500-ee80-11e9-98a8-eec50f564dfa.png">

I hope this makes sense but let me know if not!

**Comment by natalieworth** [comment]
Hey @AwesomeAudrey just had a question for the sponsorship graphic to share with partners, should we make that for facebook, twitter, and instagram? How does that work? Do you have an idea of what content should be on it?

**Comment by AwesomeAudrey** [comment]
@natalieworth Apologies! I missed this. Twitter is the main channel we're engaging with sponsor s on. Something to the effect of "Proud to be a sponsor of #MozFest!" 
![MozFest](https://user-images.githubusercontent.com/7354847/67081526-3a2a9f80-f18f-11e9-8469-78094431134f.jpg)

**Comment by natalieworth** [comment]
Have updated the [template assets here](https://drive.google.com/drive/folders/1svUkclE9TcsYM2U66MKaPEBHlCGarD2X).

@AwesomeAudrey Let me know if you need anything more for these. I'll also be around at MozFest and can help out if you need any additional graphics made while we are there :)

**Comment by natalieworth** [comment]
I think we can close this right?
